data:extend({
                {
                    order = "a1",
                    name = Toolbars.settings.columns,
                    localised_name = "Toolbar columns",
                    localised_description = "Horizontal slot count for every toolbar page. Rows still expand and shrink automatically.",
                    setting_type = "runtime-per-user",
                    type = "int-setting",
                    default_value = 10,
                    minimum_value = 1,
                    maximum_value = 100,
                },
                {
                    order = "a2",
                    name = Toolbars.settings.tooltipDelay,
                    localised_name = "Tooltip delay [ms]",
                    setting_type = "runtime-per-user",
                    type = "int-setting",
                    default_value = 600,
                },
                {
                    order = "a3",
                    name = Toolbars.settings.tooltipRefreshInterval,
                    localised_name = "Tooltip refresh interval [tick=16.6ms]",
                    setting_type = "runtime-per-user",
                    type = "int-setting",
                    default_value = 5,
                },
                {
                    order = "a4",
                    name = Toolbars.settings.showControlsInTheTooltip,
                    localised_name = "Show controls in the tooltip",
                    setting_type = "runtime-per-user",
                    type = "bool-setting",
                    default_value = true,
                },
                {
                    order = "b1",
                    name = Toolbars.settings.characterInventoriesContentRefreshInterval,
                    localised_name = "Character inventories content refresh interval [tick=16.6ms]",
                    localised_description = "Find your tradeoff between character inventories refresh cost, responsiveness and slots count change cost",
                    setting_type = "runtime-per-user",
                    type = "int-setting",
                    default_value = 1,
                },
                {
                    order = "c1",
                    name = Toolbars.settings.showVehicleInventoriesContent,
                    localised_name = "Show vehicle inventories content",
                    localised_description = "Turn it off if you don’t like it or want to avoid its performance cost",
                    setting_type = "runtime-per-user",
                    type = "bool-setting",
                    default_value = true,
                },
                {
                    order = "c2",
                    name = Toolbars.settings.vehicleInventoriesContentRefreshInterval,
                    localised_name = "Vehicle inventories content refresh interval [tick=16.6ms]",
                    localised_description = "Find your tradeoff between vehicle inventories content refresh cost, responsiveness and slots count change cost",
                    setting_type = "runtime-per-user",
                    type = "int-setting",
                    default_value = 5,
                },
                {
                    order = "d1",
                    name = Toolbars.settings.showLogisticNetworksContent,
                    localised_name = "Show logistic networks content",
                    localised_description = "Turn it off if you don’t like it or want to avoid its performance cost",
                    setting_type = "runtime-per-user",
                    type = "bool-setting",
                    default_value = true,
                },
                {
                    order = "d2",
                    name = Toolbars.settings.logisticNetworksContentRefreshInterval,
                    localised_name = "Logistic networks content refresh interval [tick=16.6ms]",
                    localised_description = "Find your tradeoff between logistic networks content refresh cost, responsiveness and slots count change cost",
                    setting_type = "runtime-per-user",
                    type = "int-setting",
                    default_value = 5,
                },
            })
